version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.m.daocloud.io/library/elasticsearch:8.11.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.11.3
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  #     ELASTICSEARCH_USERNAME: elastic
  #     ELASTICSEARCH_PASSWORD: changeme
  #   networks:
  #     - elastic

  # app:
  #   image: music-es-kafka-app
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - kafka
  #     - elasticsearch
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #     ELASTICSEARCH_HOST: http://elasticsearch:9200
  #   networks:
  #     - elastic

volumes:
  esdata:

networks:
  elastic:
    driver: bridge